# Generated by Django 3.1.4 on 2020-12-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201128_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(null=True),
        ),
    ]
