# Generated by Django 3.1.4 on 2021-04-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210404_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='6782.jpg', upload_to='{{MEDIA_URL}}images/'),
        ),
    ]
