# Generated by Django 3.1.4 on 2021-04-12 08:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20210408_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectpart1text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projectpart2text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projectpart3text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projectpart4text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projectpart5text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
